version: '3'

services:
  mongodb:
    image: mongo:latest
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s

  primes-server:
    image: demo/primes-server-mongo:latest
    deploy:
      replicas: 3
    environment:
      MONGODB_HOST: mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 10s
      timeout: 2s
    links:
      - mongodb

  proxy:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - primes-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
