version: '3'

services:
  primes-server:
    image: demo/primes-server:latest
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 10s
      timeout: 2s

  proxy:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - primes-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock