FROM centos:7

LABEL description="primes server with Mongo database"
LABEL maintainer="Thomas Lehmann"

RUN yum -y install python-setuptools
RUN easy_install pip
RUN pip install Flask Flask-MongoAlchemy

RUN mkdir -p /application
ADD src/primes_server_mongo.py /application

EXPOSE 5000/tcp
ENV FLASK_APP=/application/primes_server_mongo.py

ENTRYPOINT [ "flask", "run", "--host=0.0.0.0" ]